# TASK level variables
- name: variables from PLAY level
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Siva"
    Duration: "110HRS"
    institute: "cloudwithsiva"
  tasks:
  - name: check variables
    vars: #task level
      Course: "DevOps with AWS"
      Trainer: "SivaKumar"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}},Institute is {{institute}} Duration is {{Duration}}"
