- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml # this is file name we stored variables in this folder, it will that file
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"