- name: variables from command
  hosts: localhost
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"


#we have to give variables on command like as show in below command
# ansible-playbook -i  inventory.ini -e ansible_user=centos -e ansible_password=DevOps321 -e "PERSON=Siva" -e "WISHES=Morning" 09-vars-from-args.yaml