- name: checking data type
  hosts: localhost
  vars:
   Name: Basha #key value
   skills: #Skills is a list type
   - Devops
   - Shell
   - Ansible
   - Linux
   Experience: # Experience is map type. It contains key value pairs
      DevOps: 7
      AWS: 6
      Docker: 4
    Trainer: true # boolean
  tasks:
   - name: print the key value
     ansible.builtin.debug:
     msg: "name : {{Name}}"

   - name: print the list values
     ansible.builtin.debug:
     msg: "name : {{skills}}"

   - name: print the map values
     ansible.builtin.debug:
     msg: "name : {{Experience}}"

   - name: print the boolean ture or false
     ansible.builtin.debug:
     msg: "name : {{Trainer}}"      
  