- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: user #user is a variable name
    ignore_errors: true # ansilbe will not exit even it got error
  
  - name: print variable value
    ansible.builtin.debug:
      msg: "User output is: {{user}}"
  
  - name: print exit status or return code
    ansible.builtin.debug:
      msg: "status is: {{user.rc}}" #in ansible exit status we are use rc

  - name: create user #if above condition is not sucess then only this condition run
    ansible.builtin.user:
      name: roboshop
    when: user.rc != 0 #condition