- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages one by one
    ansible.builtin.package:
     name: "{{item}}" # item is a default keyword
     state: present
  loop:
    - git
    - mysql
    - postfix