- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install or un-install packages
    ansible.builtin.package:
    name: "{{iteam.name}}"
    state: "{{iteam.state}}" # item is a default keyword
  loop:
    - {name: 'git', state: 'present'} # item
    - {name: 'mysql', state: 'absent'}
    - {name: 'postfix', state: 'absent'}
    - {name: 'nginx', state: 'present'}